/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IO_Map.h
**     Project     : PWM_PE
**     Processor   : SKEAZN64MLH2
**     Component   : IO_Map
**     Version     : Driver 01.00
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-05-21, 12:48, # CodeGen: 0
**     Abstract    :
**         IO_Map.h - implements an IO device's mapping. 
**         This module contains symbol definitions of all peripheral 
**         registers and bits. 
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IO_Map.h
** @version 01.00
** @brief
**         IO_Map.h - implements an IO device's mapping. 
**         This module contains symbol definitions of all peripheral 
**         registers and bits. 
*/         
/*!
**  @addtogroup IO_Map_module IO_Map module documentation
**  @{
*/         

#ifndef __IO_Map_H
#define __IO_Map_H

#include "SKEAZN642.h"


/* ----------------------------------------------------------------------------
   -- NVIC
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup NVIC_Peripheral NVIC
 * @{
 */

/** NVIC - Peripheral register structure */
typedef struct NVIC_MemMap {
  uint32_t ISER;                                   /**< Interrupt Set Enable Register, offset: 0x0 */
  uint8_t RESERVED_0[124];
  uint32_t ICER;                                   /**< Interrupt Clear Enable Register, offset: 0x80 */
  uint8_t RESERVED_1[124];
  uint32_t ISPR;                                   /**< Interrupt Set Pending Register, offset: 0x100 */
  uint8_t RESERVED_2[124];
  uint32_t ICPR;                                   /**< Interrupt Clear Pending Register, offset: 0x180 */
  uint8_t RESERVED_3[380];
  uint32_t IP[8];                                  /**< Interrupt Priority Register 0..Interrupt Priority Register 7, array offset: 0x300, array step: 0x4 */
} volatile *NVIC_MemMapPtr;


/* ----------------------------------------------------------------------------
   -- NVIC - Register accessor macros
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup NVIC_Register_Accessor_Macros NVIC - Register accessor macros
 * @{
 */


/* NVIC - Register accessors */
#define NVIC_ISER_REG(base)                      ((base)->ISER)
#define NVIC_ICER_REG(base)                      ((base)->ICER)
#define NVIC_ISPR_REG(base)                      ((base)->ISPR)
#define NVIC_ICPR_REG(base)                      ((base)->ICPR)
#define NVIC_IP_REG(base,index)                  ((base)->IP[index])
#define NVIC_IP_COUNT                            8

/*!
 * @}
 */ /* end of group NVIC_Register_Accessor_Macros */


/* ----------------------------------------------------------------------------
   -- NVIC Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup NVIC_Register_Masks NVIC Register Masks
 * @{
 */

/* ISER Bit Fields */
#define NVIC_ISER_SETENA0_MASK                   0x1u
#define NVIC_ISER_SETENA0_SHIFT                  0
#define NVIC_ISER_SETENA0_WIDTH                  1
#define NVIC_ISER_SETENA0(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA0_SHIFT))&NVIC_ISER_SETENA0_MASK)
#define NVIC_ISER_SETENA1_MASK                   0x2u
#define NVIC_ISER_SETENA1_SHIFT                  1
#define NVIC_ISER_SETENA1_WIDTH                  1
#define NVIC_ISER_SETENA1(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA1_SHIFT))&NVIC_ISER_SETENA1_MASK)
#define NVIC_ISER_SETENA2_MASK                   0x4u
#define NVIC_ISER_SETENA2_SHIFT                  2
#define NVIC_ISER_SETENA2_WIDTH                  1
#define NVIC_ISER_SETENA2(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA2_SHIFT))&NVIC_ISER_SETENA2_MASK)
#define NVIC_ISER_SETENA3_MASK                   0x8u
#define NVIC_ISER_SETENA3_SHIFT                  3
#define NVIC_ISER_SETENA3_WIDTH                  1
#define NVIC_ISER_SETENA3(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA3_SHIFT))&NVIC_ISER_SETENA3_MASK)
#define NVIC_ISER_SETENA4_MASK                   0x10u
#define NVIC_ISER_SETENA4_SHIFT                  4
#define NVIC_ISER_SETENA4_WIDTH                  1
#define NVIC_ISER_SETENA4(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA4_SHIFT))&NVIC_ISER_SETENA4_MASK)
#define NVIC_ISER_SETENA5_MASK                   0x20u
#define NVIC_ISER_SETENA5_SHIFT                  5
#define NVIC_ISER_SETENA5_WIDTH                  1
#define NVIC_ISER_SETENA5(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA5_SHIFT))&NVIC_ISER_SETENA5_MASK)
#define NVIC_ISER_SETENA6_MASK                   0x40u
#define NVIC_ISER_SETENA6_SHIFT                  6
#define NVIC_ISER_SETENA6_WIDTH                  1
#define NVIC_ISER_SETENA6(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA6_SHIFT))&NVIC_ISER_SETENA6_MASK)
#define NVIC_ISER_SETENA7_MASK                   0x80u
#define NVIC_ISER_SETENA7_SHIFT                  7
#define NVIC_ISER_SETENA7_WIDTH                  1
#define NVIC_ISER_SETENA7(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA7_SHIFT))&NVIC_ISER_SETENA7_MASK)
#define NVIC_ISER_SETENA8_MASK                   0x100u
#define NVIC_ISER_SETENA8_SHIFT                  8
#define NVIC_ISER_SETENA8_WIDTH                  1
#define NVIC_ISER_SETENA8(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA8_SHIFT))&NVIC_ISER_SETENA8_MASK)
#define NVIC_ISER_SETENA9_MASK                   0x200u
#define NVIC_ISER_SETENA9_SHIFT                  9
#define NVIC_ISER_SETENA9_WIDTH                  1
#define NVIC_ISER_SETENA9(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA9_SHIFT))&NVIC_ISER_SETENA9_MASK)
#define NVIC_ISER_SETENA10_MASK                  0x400u
#define NVIC_ISER_SETENA10_SHIFT                 10
#define NVIC_ISER_SETENA10_WIDTH                 1
#define NVIC_ISER_SETENA10(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA10_SHIFT))&NVIC_ISER_SETENA10_MASK)
#define NVIC_ISER_SETENA11_MASK                  0x800u
#define NVIC_ISER_SETENA11_SHIFT                 11
#define NVIC_ISER_SETENA11_WIDTH                 1
#define NVIC_ISER_SETENA11(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA11_SHIFT))&NVIC_ISER_SETENA11_MASK)
#define NVIC_ISER_SETENA12_MASK                  0x1000u
#define NVIC_ISER_SETENA12_SHIFT                 12
#define NVIC_ISER_SETENA12_WIDTH                 1
#define NVIC_ISER_SETENA12(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA12_SHIFT))&NVIC_ISER_SETENA12_MASK)
#define NVIC_ISER_SETENA13_MASK                  0x2000u
#define NVIC_ISER_SETENA13_SHIFT                 13
#define NVIC_ISER_SETENA13_WIDTH                 1
#define NVIC_ISER_SETENA13(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA13_SHIFT))&NVIC_ISER_SETENA13_MASK)
#define NVIC_ISER_SETENA14_MASK                  0x4000u
#define NVIC_ISER_SETENA14_SHIFT                 14
#define NVIC_ISER_SETENA14_WIDTH                 1
#define NVIC_ISER_SETENA14(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA14_SHIFT))&NVIC_ISER_SETENA14_MASK)
#define NVIC_ISER_SETENA15_MASK                  0x8000u
#define NVIC_ISER_SETENA15_SHIFT                 15
#define NVIC_ISER_SETENA15_WIDTH                 1
#define NVIC_ISER_SETENA15(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA15_SHIFT))&NVIC_ISER_SETENA15_MASK)
#define NVIC_ISER_SETENA16_MASK                  0x10000u
#define NVIC_ISER_SETENA16_SHIFT                 16
#define NVIC_ISER_SETENA16_WIDTH                 1
#define NVIC_ISER_SETENA16(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA16_SHIFT))&NVIC_ISER_SETENA16_MASK)
#define NVIC_ISER_SETENA17_MASK                  0x20000u
#define NVIC_ISER_SETENA17_SHIFT                 17
#define NVIC_ISER_SETENA17_WIDTH                 1
#define NVIC_ISER_SETENA17(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA17_SHIFT))&NVIC_ISER_SETENA17_MASK)
#define NVIC_ISER_SETENA18_MASK                  0x40000u
#define NVIC_ISER_SETENA18_SHIFT                 18
#define NVIC_ISER_SETENA18_WIDTH                 1
#define NVIC_ISER_SETENA18(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA18_SHIFT))&NVIC_ISER_SETENA18_MASK)
#define NVIC_ISER_SETENA19_MASK                  0x80000u
#define NVIC_ISER_SETENA19_SHIFT                 19
#define NVIC_ISER_SETENA19_WIDTH                 1
#define NVIC_ISER_SETENA19(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA19_SHIFT))&NVIC_ISER_SETENA19_MASK)
#define NVIC_ISER_SETENA20_MASK                  0x100000u
#define NVIC_ISER_SETENA20_SHIFT                 20
#define NVIC_ISER_SETENA20_WIDTH                 1
#define NVIC_ISER_SETENA20(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA20_SHIFT))&NVIC_ISER_SETENA20_MASK)
#define NVIC_ISER_SETENA21_MASK                  0x200000u
#define NVIC_ISER_SETENA21_SHIFT                 21
#define NVIC_ISER_SETENA21_WIDTH                 1
#define NVIC_ISER_SETENA21(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA21_SHIFT))&NVIC_ISER_SETENA21_MASK)
#define NVIC_ISER_SETENA22_MASK                  0x400000u
#define NVIC_ISER_SETENA22_SHIFT                 22
#define NVIC_ISER_SETENA22_WIDTH                 1
#define NVIC_ISER_SETENA22(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA22_SHIFT))&NVIC_ISER_SETENA22_MASK)
#define NVIC_ISER_SETENA23_MASK                  0x800000u
#define NVIC_ISER_SETENA23_SHIFT                 23
#define NVIC_ISER_SETENA23_WIDTH                 1
#define NVIC_ISER_SETENA23(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA23_SHIFT))&NVIC_ISER_SETENA23_MASK)
#define NVIC_ISER_SETENA24_MASK                  0x1000000u
#define NVIC_ISER_SETENA24_SHIFT                 24
#define NVIC_ISER_SETENA24_WIDTH                 1
#define NVIC_ISER_SETENA24(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA24_SHIFT))&NVIC_ISER_SETENA24_MASK)
#define NVIC_ISER_SETENA25_MASK                  0x2000000u
#define NVIC_ISER_SETENA25_SHIFT                 25
#define NVIC_ISER_SETENA25_WIDTH                 1
#define NVIC_ISER_SETENA25(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA25_SHIFT))&NVIC_ISER_SETENA25_MASK)
#define NVIC_ISER_SETENA26_MASK                  0x4000000u
#define NVIC_ISER_SETENA26_SHIFT                 26
#define NVIC_ISER_SETENA26_WIDTH                 1
#define NVIC_ISER_SETENA26(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA26_SHIFT))&NVIC_ISER_SETENA26_MASK)
#define NVIC_ISER_SETENA27_MASK                  0x8000000u
#define NVIC_ISER_SETENA27_SHIFT                 27
#define NVIC_ISER_SETENA27_WIDTH                 1
#define NVIC_ISER_SETENA27(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA27_SHIFT))&NVIC_ISER_SETENA27_MASK)
#define NVIC_ISER_SETENA28_MASK                  0x10000000u
#define NVIC_ISER_SETENA28_SHIFT                 28
#define NVIC_ISER_SETENA28_WIDTH                 1
#define NVIC_ISER_SETENA28(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA28_SHIFT))&NVIC_ISER_SETENA28_MASK)
#define NVIC_ISER_SETENA29_MASK                  0x20000000u
#define NVIC_ISER_SETENA29_SHIFT                 29
#define NVIC_ISER_SETENA29_WIDTH                 1
#define NVIC_ISER_SETENA29(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA29_SHIFT))&NVIC_ISER_SETENA29_MASK)
#define NVIC_ISER_SETENA30_MASK                  0x40000000u
#define NVIC_ISER_SETENA30_SHIFT                 30
#define NVIC_ISER_SETENA30_WIDTH                 1
#define NVIC_ISER_SETENA30(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA30_SHIFT))&NVIC_ISER_SETENA30_MASK)
#define NVIC_ISER_SETENA31_MASK                  0x80000000u
#define NVIC_ISER_SETENA31_SHIFT                 31
#define NVIC_ISER_SETENA31_WIDTH                 1
#define NVIC_ISER_SETENA31(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISER_SETENA31_SHIFT))&NVIC_ISER_SETENA31_MASK)
/* ICER Bit Fields */
#define NVIC_ICER_CLRENA0_MASK                   0x1u
#define NVIC_ICER_CLRENA0_SHIFT                  0
#define NVIC_ICER_CLRENA0_WIDTH                  1
#define NVIC_ICER_CLRENA0(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA0_SHIFT))&NVIC_ICER_CLRENA0_MASK)
#define NVIC_ICER_CLRENA1_MASK                   0x2u
#define NVIC_ICER_CLRENA1_SHIFT                  1
#define NVIC_ICER_CLRENA1_WIDTH                  1
#define NVIC_ICER_CLRENA1(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA1_SHIFT))&NVIC_ICER_CLRENA1_MASK)
#define NVIC_ICER_CLRENA2_MASK                   0x4u
#define NVIC_ICER_CLRENA2_SHIFT                  2
#define NVIC_ICER_CLRENA2_WIDTH                  1
#define NVIC_ICER_CLRENA2(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA2_SHIFT))&NVIC_ICER_CLRENA2_MASK)
#define NVIC_ICER_CLRENA3_MASK                   0x8u
#define NVIC_ICER_CLRENA3_SHIFT                  3
#define NVIC_ICER_CLRENA3_WIDTH                  1
#define NVIC_ICER_CLRENA3(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA3_SHIFT))&NVIC_ICER_CLRENA3_MASK)
#define NVIC_ICER_CLRENA4_MASK                   0x10u
#define NVIC_ICER_CLRENA4_SHIFT                  4
#define NVIC_ICER_CLRENA4_WIDTH                  1
#define NVIC_ICER_CLRENA4(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA4_SHIFT))&NVIC_ICER_CLRENA4_MASK)
#define NVIC_ICER_CLRENA5_MASK                   0x20u
#define NVIC_ICER_CLRENA5_SHIFT                  5
#define NVIC_ICER_CLRENA5_WIDTH                  1
#define NVIC_ICER_CLRENA5(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA5_SHIFT))&NVIC_ICER_CLRENA5_MASK)
#define NVIC_ICER_CLRENA6_MASK                   0x40u
#define NVIC_ICER_CLRENA6_SHIFT                  6
#define NVIC_ICER_CLRENA6_WIDTH                  1
#define NVIC_ICER_CLRENA6(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA6_SHIFT))&NVIC_ICER_CLRENA6_MASK)
#define NVIC_ICER_CLRENA7_MASK                   0x80u
#define NVIC_ICER_CLRENA7_SHIFT                  7
#define NVIC_ICER_CLRENA7_WIDTH                  1
#define NVIC_ICER_CLRENA7(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA7_SHIFT))&NVIC_ICER_CLRENA7_MASK)
#define NVIC_ICER_CLRENA8_MASK                   0x100u
#define NVIC_ICER_CLRENA8_SHIFT                  8
#define NVIC_ICER_CLRENA8_WIDTH                  1
#define NVIC_ICER_CLRENA8(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA8_SHIFT))&NVIC_ICER_CLRENA8_MASK)
#define NVIC_ICER_CLRENA9_MASK                   0x200u
#define NVIC_ICER_CLRENA9_SHIFT                  9
#define NVIC_ICER_CLRENA9_WIDTH                  1
#define NVIC_ICER_CLRENA9(x)                     (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA9_SHIFT))&NVIC_ICER_CLRENA9_MASK)
#define NVIC_ICER_CLRENA10_MASK                  0x400u
#define NVIC_ICER_CLRENA10_SHIFT                 10
#define NVIC_ICER_CLRENA10_WIDTH                 1
#define NVIC_ICER_CLRENA10(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA10_SHIFT))&NVIC_ICER_CLRENA10_MASK)
#define NVIC_ICER_CLRENA11_MASK                  0x800u
#define NVIC_ICER_CLRENA11_SHIFT                 11
#define NVIC_ICER_CLRENA11_WIDTH                 1
#define NVIC_ICER_CLRENA11(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA11_SHIFT))&NVIC_ICER_CLRENA11_MASK)
#define NVIC_ICER_CLRENA12_MASK                  0x1000u
#define NVIC_ICER_CLRENA12_SHIFT                 12
#define NVIC_ICER_CLRENA12_WIDTH                 1
#define NVIC_ICER_CLRENA12(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA12_SHIFT))&NVIC_ICER_CLRENA12_MASK)
#define NVIC_ICER_CLRENA13_MASK                  0x2000u
#define NVIC_ICER_CLRENA13_SHIFT                 13
#define NVIC_ICER_CLRENA13_WIDTH                 1
#define NVIC_ICER_CLRENA13(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA13_SHIFT))&NVIC_ICER_CLRENA13_MASK)
#define NVIC_ICER_CLRENA14_MASK                  0x4000u
#define NVIC_ICER_CLRENA14_SHIFT                 14
#define NVIC_ICER_CLRENA14_WIDTH                 1
#define NVIC_ICER_CLRENA14(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA14_SHIFT))&NVIC_ICER_CLRENA14_MASK)
#define NVIC_ICER_CLRENA15_MASK                  0x8000u
#define NVIC_ICER_CLRENA15_SHIFT                 15
#define NVIC_ICER_CLRENA15_WIDTH                 1
#define NVIC_ICER_CLRENA15(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA15_SHIFT))&NVIC_ICER_CLRENA15_MASK)
#define NVIC_ICER_CLRENA16_MASK                  0x10000u
#define NVIC_ICER_CLRENA16_SHIFT                 16
#define NVIC_ICER_CLRENA16_WIDTH                 1
#define NVIC_ICER_CLRENA16(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA16_SHIFT))&NVIC_ICER_CLRENA16_MASK)
#define NVIC_ICER_CLRENA17_MASK                  0x20000u
#define NVIC_ICER_CLRENA17_SHIFT                 17
#define NVIC_ICER_CLRENA17_WIDTH                 1
#define NVIC_ICER_CLRENA17(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA17_SHIFT))&NVIC_ICER_CLRENA17_MASK)
#define NVIC_ICER_CLRENA18_MASK                  0x40000u
#define NVIC_ICER_CLRENA18_SHIFT                 18
#define NVIC_ICER_CLRENA18_WIDTH                 1
#define NVIC_ICER_CLRENA18(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA18_SHIFT))&NVIC_ICER_CLRENA18_MASK)
#define NVIC_ICER_CLRENA19_MASK                  0x80000u
#define NVIC_ICER_CLRENA19_SHIFT                 19
#define NVIC_ICER_CLRENA19_WIDTH                 1
#define NVIC_ICER_CLRENA19(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA19_SHIFT))&NVIC_ICER_CLRENA19_MASK)
#define NVIC_ICER_CLRENA20_MASK                  0x100000u
#define NVIC_ICER_CLRENA20_SHIFT                 20
#define NVIC_ICER_CLRENA20_WIDTH                 1
#define NVIC_ICER_CLRENA20(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA20_SHIFT))&NVIC_ICER_CLRENA20_MASK)
#define NVIC_ICER_CLRENA21_MASK                  0x200000u
#define NVIC_ICER_CLRENA21_SHIFT                 21
#define NVIC_ICER_CLRENA21_WIDTH                 1
#define NVIC_ICER_CLRENA21(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA21_SHIFT))&NVIC_ICER_CLRENA21_MASK)
#define NVIC_ICER_CLRENA22_MASK                  0x400000u
#define NVIC_ICER_CLRENA22_SHIFT                 22
#define NVIC_ICER_CLRENA22_WIDTH                 1
#define NVIC_ICER_CLRENA22(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA22_SHIFT))&NVIC_ICER_CLRENA22_MASK)
#define NVIC_ICER_CLRENA23_MASK                  0x800000u
#define NVIC_ICER_CLRENA23_SHIFT                 23
#define NVIC_ICER_CLRENA23_WIDTH                 1
#define NVIC_ICER_CLRENA23(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA23_SHIFT))&NVIC_ICER_CLRENA23_MASK)
#define NVIC_ICER_CLRENA24_MASK                  0x1000000u
#define NVIC_ICER_CLRENA24_SHIFT                 24
#define NVIC_ICER_CLRENA24_WIDTH                 1
#define NVIC_ICER_CLRENA24(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA24_SHIFT))&NVIC_ICER_CLRENA24_MASK)
#define NVIC_ICER_CLRENA25_MASK                  0x2000000u
#define NVIC_ICER_CLRENA25_SHIFT                 25
#define NVIC_ICER_CLRENA25_WIDTH                 1
#define NVIC_ICER_CLRENA25(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA25_SHIFT))&NVIC_ICER_CLRENA25_MASK)
#define NVIC_ICER_CLRENA26_MASK                  0x4000000u
#define NVIC_ICER_CLRENA26_SHIFT                 26
#define NVIC_ICER_CLRENA26_WIDTH                 1
#define NVIC_ICER_CLRENA26(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA26_SHIFT))&NVIC_ICER_CLRENA26_MASK)
#define NVIC_ICER_CLRENA27_MASK                  0x8000000u
#define NVIC_ICER_CLRENA27_SHIFT                 27
#define NVIC_ICER_CLRENA27_WIDTH                 1
#define NVIC_ICER_CLRENA27(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA27_SHIFT))&NVIC_ICER_CLRENA27_MASK)
#define NVIC_ICER_CLRENA28_MASK                  0x10000000u
#define NVIC_ICER_CLRENA28_SHIFT                 28
#define NVIC_ICER_CLRENA28_WIDTH                 1
#define NVIC_ICER_CLRENA28(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA28_SHIFT))&NVIC_ICER_CLRENA28_MASK)
#define NVIC_ICER_CLRENA29_MASK                  0x20000000u
#define NVIC_ICER_CLRENA29_SHIFT                 29
#define NVIC_ICER_CLRENA29_WIDTH                 1
#define NVIC_ICER_CLRENA29(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA29_SHIFT))&NVIC_ICER_CLRENA29_MASK)
#define NVIC_ICER_CLRENA30_MASK                  0x40000000u
#define NVIC_ICER_CLRENA30_SHIFT                 30
#define NVIC_ICER_CLRENA30_WIDTH                 1
#define NVIC_ICER_CLRENA30(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA30_SHIFT))&NVIC_ICER_CLRENA30_MASK)
#define NVIC_ICER_CLRENA31_MASK                  0x80000000u
#define NVIC_ICER_CLRENA31_SHIFT                 31
#define NVIC_ICER_CLRENA31_WIDTH                 1
#define NVIC_ICER_CLRENA31(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICER_CLRENA31_SHIFT))&NVIC_ICER_CLRENA31_MASK)
/* ISPR Bit Fields */
#define NVIC_ISPR_SETPEND0_MASK                  0x1u
#define NVIC_ISPR_SETPEND0_SHIFT                 0
#define NVIC_ISPR_SETPEND0_WIDTH                 1
#define NVIC_ISPR_SETPEND0(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND0_SHIFT))&NVIC_ISPR_SETPEND0_MASK)
#define NVIC_ISPR_SETPEND1_MASK                  0x2u
#define NVIC_ISPR_SETPEND1_SHIFT                 1
#define NVIC_ISPR_SETPEND1_WIDTH                 1
#define NVIC_ISPR_SETPEND1(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND1_SHIFT))&NVIC_ISPR_SETPEND1_MASK)
#define NVIC_ISPR_SETPEND2_MASK                  0x4u
#define NVIC_ISPR_SETPEND2_SHIFT                 2
#define NVIC_ISPR_SETPEND2_WIDTH                 1
#define NVIC_ISPR_SETPEND2(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND2_SHIFT))&NVIC_ISPR_SETPEND2_MASK)
#define NVIC_ISPR_SETPEND3_MASK                  0x8u
#define NVIC_ISPR_SETPEND3_SHIFT                 3
#define NVIC_ISPR_SETPEND3_WIDTH                 1
#define NVIC_ISPR_SETPEND3(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND3_SHIFT))&NVIC_ISPR_SETPEND3_MASK)
#define NVIC_ISPR_SETPEND4_MASK                  0x10u
#define NVIC_ISPR_SETPEND4_SHIFT                 4
#define NVIC_ISPR_SETPEND4_WIDTH                 1
#define NVIC_ISPR_SETPEND4(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND4_SHIFT))&NVIC_ISPR_SETPEND4_MASK)
#define NVIC_ISPR_SETPEND5_MASK                  0x20u
#define NVIC_ISPR_SETPEND5_SHIFT                 5
#define NVIC_ISPR_SETPEND5_WIDTH                 1
#define NVIC_ISPR_SETPEND5(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND5_SHIFT))&NVIC_ISPR_SETPEND5_MASK)
#define NVIC_ISPR_SETPEND6_MASK                  0x40u
#define NVIC_ISPR_SETPEND6_SHIFT                 6
#define NVIC_ISPR_SETPEND6_WIDTH                 1
#define NVIC_ISPR_SETPEND6(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND6_SHIFT))&NVIC_ISPR_SETPEND6_MASK)
#define NVIC_ISPR_SETPEND7_MASK                  0x80u
#define NVIC_ISPR_SETPEND7_SHIFT                 7
#define NVIC_ISPR_SETPEND7_WIDTH                 1
#define NVIC_ISPR_SETPEND7(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND7_SHIFT))&NVIC_ISPR_SETPEND7_MASK)
#define NVIC_ISPR_SETPEND8_MASK                  0x100u
#define NVIC_ISPR_SETPEND8_SHIFT                 8
#define NVIC_ISPR_SETPEND8_WIDTH                 1
#define NVIC_ISPR_SETPEND8(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND8_SHIFT))&NVIC_ISPR_SETPEND8_MASK)
#define NVIC_ISPR_SETPEND9_MASK                  0x200u
#define NVIC_ISPR_SETPEND9_SHIFT                 9
#define NVIC_ISPR_SETPEND9_WIDTH                 1
#define NVIC_ISPR_SETPEND9(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND9_SHIFT))&NVIC_ISPR_SETPEND9_MASK)
#define NVIC_ISPR_SETPEND10_MASK                 0x400u
#define NVIC_ISPR_SETPEND10_SHIFT                10
#define NVIC_ISPR_SETPEND10_WIDTH                1
#define NVIC_ISPR_SETPEND10(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND10_SHIFT))&NVIC_ISPR_SETPEND10_MASK)
#define NVIC_ISPR_SETPEND11_MASK                 0x800u
#define NVIC_ISPR_SETPEND11_SHIFT                11
#define NVIC_ISPR_SETPEND11_WIDTH                1
#define NVIC_ISPR_SETPEND11(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND11_SHIFT))&NVIC_ISPR_SETPEND11_MASK)
#define NVIC_ISPR_SETPEND12_MASK                 0x1000u
#define NVIC_ISPR_SETPEND12_SHIFT                12
#define NVIC_ISPR_SETPEND12_WIDTH                1
#define NVIC_ISPR_SETPEND12(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND12_SHIFT))&NVIC_ISPR_SETPEND12_MASK)
#define NVIC_ISPR_SETPEND13_MASK                 0x2000u
#define NVIC_ISPR_SETPEND13_SHIFT                13
#define NVIC_ISPR_SETPEND13_WIDTH                1
#define NVIC_ISPR_SETPEND13(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND13_SHIFT))&NVIC_ISPR_SETPEND13_MASK)
#define NVIC_ISPR_SETPEND14_MASK                 0x4000u
#define NVIC_ISPR_SETPEND14_SHIFT                14
#define NVIC_ISPR_SETPEND14_WIDTH                1
#define NVIC_ISPR_SETPEND14(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND14_SHIFT))&NVIC_ISPR_SETPEND14_MASK)
#define NVIC_ISPR_SETPEND15_MASK                 0x8000u
#define NVIC_ISPR_SETPEND15_SHIFT                15
#define NVIC_ISPR_SETPEND15_WIDTH                1
#define NVIC_ISPR_SETPEND15(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND15_SHIFT))&NVIC_ISPR_SETPEND15_MASK)
#define NVIC_ISPR_SETPEND16_MASK                 0x10000u
#define NVIC_ISPR_SETPEND16_SHIFT                16
#define NVIC_ISPR_SETPEND16_WIDTH                1
#define NVIC_ISPR_SETPEND16(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND16_SHIFT))&NVIC_ISPR_SETPEND16_MASK)
#define NVIC_ISPR_SETPEND17_MASK                 0x20000u
#define NVIC_ISPR_SETPEND17_SHIFT                17
#define NVIC_ISPR_SETPEND17_WIDTH                1
#define NVIC_ISPR_SETPEND17(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND17_SHIFT))&NVIC_ISPR_SETPEND17_MASK)
#define NVIC_ISPR_SETPEND18_MASK                 0x40000u
#define NVIC_ISPR_SETPEND18_SHIFT                18
#define NVIC_ISPR_SETPEND18_WIDTH                1
#define NVIC_ISPR_SETPEND18(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND18_SHIFT))&NVIC_ISPR_SETPEND18_MASK)
#define NVIC_ISPR_SETPEND19_MASK                 0x80000u
#define NVIC_ISPR_SETPEND19_SHIFT                19
#define NVIC_ISPR_SETPEND19_WIDTH                1
#define NVIC_ISPR_SETPEND19(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND19_SHIFT))&NVIC_ISPR_SETPEND19_MASK)
#define NVIC_ISPR_SETPEND20_MASK                 0x100000u
#define NVIC_ISPR_SETPEND20_SHIFT                20
#define NVIC_ISPR_SETPEND20_WIDTH                1
#define NVIC_ISPR_SETPEND20(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND20_SHIFT))&NVIC_ISPR_SETPEND20_MASK)
#define NVIC_ISPR_SETPEND21_MASK                 0x200000u
#define NVIC_ISPR_SETPEND21_SHIFT                21
#define NVIC_ISPR_SETPEND21_WIDTH                1
#define NVIC_ISPR_SETPEND21(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND21_SHIFT))&NVIC_ISPR_SETPEND21_MASK)
#define NVIC_ISPR_SETPEND22_MASK                 0x400000u
#define NVIC_ISPR_SETPEND22_SHIFT                22
#define NVIC_ISPR_SETPEND22_WIDTH                1
#define NVIC_ISPR_SETPEND22(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND22_SHIFT))&NVIC_ISPR_SETPEND22_MASK)
#define NVIC_ISPR_SETPEND23_MASK                 0x800000u
#define NVIC_ISPR_SETPEND23_SHIFT                23
#define NVIC_ISPR_SETPEND23_WIDTH                1
#define NVIC_ISPR_SETPEND23(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND23_SHIFT))&NVIC_ISPR_SETPEND23_MASK)
#define NVIC_ISPR_SETPEND24_MASK                 0x1000000u
#define NVIC_ISPR_SETPEND24_SHIFT                24
#define NVIC_ISPR_SETPEND24_WIDTH                1
#define NVIC_ISPR_SETPEND24(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND24_SHIFT))&NVIC_ISPR_SETPEND24_MASK)
#define NVIC_ISPR_SETPEND25_MASK                 0x2000000u
#define NVIC_ISPR_SETPEND25_SHIFT                25
#define NVIC_ISPR_SETPEND25_WIDTH                1
#define NVIC_ISPR_SETPEND25(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND25_SHIFT))&NVIC_ISPR_SETPEND25_MASK)
#define NVIC_ISPR_SETPEND26_MASK                 0x4000000u
#define NVIC_ISPR_SETPEND26_SHIFT                26
#define NVIC_ISPR_SETPEND26_WIDTH                1
#define NVIC_ISPR_SETPEND26(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND26_SHIFT))&NVIC_ISPR_SETPEND26_MASK)
#define NVIC_ISPR_SETPEND27_MASK                 0x8000000u
#define NVIC_ISPR_SETPEND27_SHIFT                27
#define NVIC_ISPR_SETPEND27_WIDTH                1
#define NVIC_ISPR_SETPEND27(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND27_SHIFT))&NVIC_ISPR_SETPEND27_MASK)
#define NVIC_ISPR_SETPEND28_MASK                 0x10000000u
#define NVIC_ISPR_SETPEND28_SHIFT                28
#define NVIC_ISPR_SETPEND28_WIDTH                1
#define NVIC_ISPR_SETPEND28(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND28_SHIFT))&NVIC_ISPR_SETPEND28_MASK)
#define NVIC_ISPR_SETPEND29_MASK                 0x20000000u
#define NVIC_ISPR_SETPEND29_SHIFT                29
#define NVIC_ISPR_SETPEND29_WIDTH                1
#define NVIC_ISPR_SETPEND29(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND29_SHIFT))&NVIC_ISPR_SETPEND29_MASK)
#define NVIC_ISPR_SETPEND30_MASK                 0x40000000u
#define NVIC_ISPR_SETPEND30_SHIFT                30
#define NVIC_ISPR_SETPEND30_WIDTH                1
#define NVIC_ISPR_SETPEND30(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND30_SHIFT))&NVIC_ISPR_SETPEND30_MASK)
#define NVIC_ISPR_SETPEND31_MASK                 0x80000000u
#define NVIC_ISPR_SETPEND31_SHIFT                31
#define NVIC_ISPR_SETPEND31_WIDTH                1
#define NVIC_ISPR_SETPEND31(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ISPR_SETPEND31_SHIFT))&NVIC_ISPR_SETPEND31_MASK)
/* ICPR Bit Fields */
#define NVIC_ICPR_CLRPEND0_MASK                  0x1u
#define NVIC_ICPR_CLRPEND0_SHIFT                 0
#define NVIC_ICPR_CLRPEND0_WIDTH                 1
#define NVIC_ICPR_CLRPEND0(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND0_SHIFT))&NVIC_ICPR_CLRPEND0_MASK)
#define NVIC_ICPR_CLRPEND1_MASK                  0x2u
#define NVIC_ICPR_CLRPEND1_SHIFT                 1
#define NVIC_ICPR_CLRPEND1_WIDTH                 1
#define NVIC_ICPR_CLRPEND1(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND1_SHIFT))&NVIC_ICPR_CLRPEND1_MASK)
#define NVIC_ICPR_CLRPEND2_MASK                  0x4u
#define NVIC_ICPR_CLRPEND2_SHIFT                 2
#define NVIC_ICPR_CLRPEND2_WIDTH                 1
#define NVIC_ICPR_CLRPEND2(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND2_SHIFT))&NVIC_ICPR_CLRPEND2_MASK)
#define NVIC_ICPR_CLRPEND3_MASK                  0x8u
#define NVIC_ICPR_CLRPEND3_SHIFT                 3
#define NVIC_ICPR_CLRPEND3_WIDTH                 1
#define NVIC_ICPR_CLRPEND3(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND3_SHIFT))&NVIC_ICPR_CLRPEND3_MASK)
#define NVIC_ICPR_CLRPEND4_MASK                  0x10u
#define NVIC_ICPR_CLRPEND4_SHIFT                 4
#define NVIC_ICPR_CLRPEND4_WIDTH                 1
#define NVIC_ICPR_CLRPEND4(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND4_SHIFT))&NVIC_ICPR_CLRPEND4_MASK)
#define NVIC_ICPR_CLRPEND5_MASK                  0x20u
#define NVIC_ICPR_CLRPEND5_SHIFT                 5
#define NVIC_ICPR_CLRPEND5_WIDTH                 1
#define NVIC_ICPR_CLRPEND5(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND5_SHIFT))&NVIC_ICPR_CLRPEND5_MASK)
#define NVIC_ICPR_CLRPEND6_MASK                  0x40u
#define NVIC_ICPR_CLRPEND6_SHIFT                 6
#define NVIC_ICPR_CLRPEND6_WIDTH                 1
#define NVIC_ICPR_CLRPEND6(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND6_SHIFT))&NVIC_ICPR_CLRPEND6_MASK)
#define NVIC_ICPR_CLRPEND7_MASK                  0x80u
#define NVIC_ICPR_CLRPEND7_SHIFT                 7
#define NVIC_ICPR_CLRPEND7_WIDTH                 1
#define NVIC_ICPR_CLRPEND7(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND7_SHIFT))&NVIC_ICPR_CLRPEND7_MASK)
#define NVIC_ICPR_CLRPEND8_MASK                  0x100u
#define NVIC_ICPR_CLRPEND8_SHIFT                 8
#define NVIC_ICPR_CLRPEND8_WIDTH                 1
#define NVIC_ICPR_CLRPEND8(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND8_SHIFT))&NVIC_ICPR_CLRPEND8_MASK)
#define NVIC_ICPR_CLRPEND9_MASK                  0x200u
#define NVIC_ICPR_CLRPEND9_SHIFT                 9
#define NVIC_ICPR_CLRPEND9_WIDTH                 1
#define NVIC_ICPR_CLRPEND9(x)                    (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND9_SHIFT))&NVIC_ICPR_CLRPEND9_MASK)
#define NVIC_ICPR_CLRPEND10_MASK                 0x400u
#define NVIC_ICPR_CLRPEND10_SHIFT                10
#define NVIC_ICPR_CLRPEND10_WIDTH                1
#define NVIC_ICPR_CLRPEND10(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND10_SHIFT))&NVIC_ICPR_CLRPEND10_MASK)
#define NVIC_ICPR_CLRPEND11_MASK                 0x800u
#define NVIC_ICPR_CLRPEND11_SHIFT                11
#define NVIC_ICPR_CLRPEND11_WIDTH                1
#define NVIC_ICPR_CLRPEND11(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND11_SHIFT))&NVIC_ICPR_CLRPEND11_MASK)
#define NVIC_ICPR_CLRPEND12_MASK                 0x1000u
#define NVIC_ICPR_CLRPEND12_SHIFT                12
#define NVIC_ICPR_CLRPEND12_WIDTH                1
#define NVIC_ICPR_CLRPEND12(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND12_SHIFT))&NVIC_ICPR_CLRPEND12_MASK)
#define NVIC_ICPR_CLRPEND13_MASK                 0x2000u
#define NVIC_ICPR_CLRPEND13_SHIFT                13
#define NVIC_ICPR_CLRPEND13_WIDTH                1
#define NVIC_ICPR_CLRPEND13(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND13_SHIFT))&NVIC_ICPR_CLRPEND13_MASK)
#define NVIC_ICPR_CLRPEND14_MASK                 0x4000u
#define NVIC_ICPR_CLRPEND14_SHIFT                14
#define NVIC_ICPR_CLRPEND14_WIDTH                1
#define NVIC_ICPR_CLRPEND14(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND14_SHIFT))&NVIC_ICPR_CLRPEND14_MASK)
#define NVIC_ICPR_CLRPEND15_MASK                 0x8000u
#define NVIC_ICPR_CLRPEND15_SHIFT                15
#define NVIC_ICPR_CLRPEND15_WIDTH                1
#define NVIC_ICPR_CLRPEND15(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND15_SHIFT))&NVIC_ICPR_CLRPEND15_MASK)
#define NVIC_ICPR_CLRPEND16_MASK                 0x10000u
#define NVIC_ICPR_CLRPEND16_SHIFT                16
#define NVIC_ICPR_CLRPEND16_WIDTH                1
#define NVIC_ICPR_CLRPEND16(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND16_SHIFT))&NVIC_ICPR_CLRPEND16_MASK)
#define NVIC_ICPR_CLRPEND17_MASK                 0x20000u
#define NVIC_ICPR_CLRPEND17_SHIFT                17
#define NVIC_ICPR_CLRPEND17_WIDTH                1
#define NVIC_ICPR_CLRPEND17(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND17_SHIFT))&NVIC_ICPR_CLRPEND17_MASK)
#define NVIC_ICPR_CLRPEND18_MASK                 0x40000u
#define NVIC_ICPR_CLRPEND18_SHIFT                18
#define NVIC_ICPR_CLRPEND18_WIDTH                1
#define NVIC_ICPR_CLRPEND18(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND18_SHIFT))&NVIC_ICPR_CLRPEND18_MASK)
#define NVIC_ICPR_CLRPEND19_MASK                 0x80000u
#define NVIC_ICPR_CLRPEND19_SHIFT                19
#define NVIC_ICPR_CLRPEND19_WIDTH                1
#define NVIC_ICPR_CLRPEND19(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND19_SHIFT))&NVIC_ICPR_CLRPEND19_MASK)
#define NVIC_ICPR_CLRPEND20_MASK                 0x100000u
#define NVIC_ICPR_CLRPEND20_SHIFT                20
#define NVIC_ICPR_CLRPEND20_WIDTH                1
#define NVIC_ICPR_CLRPEND20(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND20_SHIFT))&NVIC_ICPR_CLRPEND20_MASK)
#define NVIC_ICPR_CLRPEND21_MASK                 0x200000u
#define NVIC_ICPR_CLRPEND21_SHIFT                21
#define NVIC_ICPR_CLRPEND21_WIDTH                1
#define NVIC_ICPR_CLRPEND21(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND21_SHIFT))&NVIC_ICPR_CLRPEND21_MASK)
#define NVIC_ICPR_CLRPEND22_MASK                 0x400000u
#define NVIC_ICPR_CLRPEND22_SHIFT                22
#define NVIC_ICPR_CLRPEND22_WIDTH                1
#define NVIC_ICPR_CLRPEND22(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND22_SHIFT))&NVIC_ICPR_CLRPEND22_MASK)
#define NVIC_ICPR_CLRPEND23_MASK                 0x800000u
#define NVIC_ICPR_CLRPEND23_SHIFT                23
#define NVIC_ICPR_CLRPEND23_WIDTH                1
#define NVIC_ICPR_CLRPEND23(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND23_SHIFT))&NVIC_ICPR_CLRPEND23_MASK)
#define NVIC_ICPR_CLRPEND24_MASK                 0x1000000u
#define NVIC_ICPR_CLRPEND24_SHIFT                24
#define NVIC_ICPR_CLRPEND24_WIDTH                1
#define NVIC_ICPR_CLRPEND24(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND24_SHIFT))&NVIC_ICPR_CLRPEND24_MASK)
#define NVIC_ICPR_CLRPEND25_MASK                 0x2000000u
#define NVIC_ICPR_CLRPEND25_SHIFT                25
#define NVIC_ICPR_CLRPEND25_WIDTH                1
#define NVIC_ICPR_CLRPEND25(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND25_SHIFT))&NVIC_ICPR_CLRPEND25_MASK)
#define NVIC_ICPR_CLRPEND26_MASK                 0x4000000u
#define NVIC_ICPR_CLRPEND26_SHIFT                26
#define NVIC_ICPR_CLRPEND26_WIDTH                1
#define NVIC_ICPR_CLRPEND26(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND26_SHIFT))&NVIC_ICPR_CLRPEND26_MASK)
#define NVIC_ICPR_CLRPEND27_MASK                 0x8000000u
#define NVIC_ICPR_CLRPEND27_SHIFT                27
#define NVIC_ICPR_CLRPEND27_WIDTH                1
#define NVIC_ICPR_CLRPEND27(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND27_SHIFT))&NVIC_ICPR_CLRPEND27_MASK)
#define NVIC_ICPR_CLRPEND28_MASK                 0x10000000u
#define NVIC_ICPR_CLRPEND28_SHIFT                28
#define NVIC_ICPR_CLRPEND28_WIDTH                1
#define NVIC_ICPR_CLRPEND28(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND28_SHIFT))&NVIC_ICPR_CLRPEND28_MASK)
#define NVIC_ICPR_CLRPEND29_MASK                 0x20000000u
#define NVIC_ICPR_CLRPEND29_SHIFT                29
#define NVIC_ICPR_CLRPEND29_WIDTH                1
#define NVIC_ICPR_CLRPEND29(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND29_SHIFT))&NVIC_ICPR_CLRPEND29_MASK)
#define NVIC_ICPR_CLRPEND30_MASK                 0x40000000u
#define NVIC_ICPR_CLRPEND30_SHIFT                30
#define NVIC_ICPR_CLRPEND30_WIDTH                1
#define NVIC_ICPR_CLRPEND30(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND30_SHIFT))&NVIC_ICPR_CLRPEND30_MASK)
#define NVIC_ICPR_CLRPEND31_MASK                 0x80000000u
#define NVIC_ICPR_CLRPEND31_SHIFT                31
#define NVIC_ICPR_CLRPEND31_WIDTH                1
#define NVIC_ICPR_CLRPEND31(x)                   (((uint32_t)(((uint32_t)(x))<<NVIC_ICPR_CLRPEND31_SHIFT))&NVIC_ICPR_CLRPEND31_MASK)
/* IP Bit Fields */
#define NVIC_IP_PRI_0_MASK                       0xFFu
#define NVIC_IP_PRI_0_SHIFT                      0
#define NVIC_IP_PRI_0_WIDTH                      8
#define NVIC_IP_PRI_0(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_0_SHIFT))&NVIC_IP_PRI_0_MASK)
#define NVIC_IP_PRI_28_MASK                      0xFFu
#define NVIC_IP_PRI_28_SHIFT                     0
#define NVIC_IP_PRI_28_WIDTH                     8
#define NVIC_IP_PRI_28(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_28_SHIFT))&NVIC_IP_PRI_28_MASK)
#define NVIC_IP_PRI_24_MASK                      0xFFu
#define NVIC_IP_PRI_24_SHIFT                     0
#define NVIC_IP_PRI_24_WIDTH                     8
#define NVIC_IP_PRI_24(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_24_SHIFT))&NVIC_IP_PRI_24_MASK)
#define NVIC_IP_PRI_20_MASK                      0xFFu
#define NVIC_IP_PRI_20_SHIFT                     0
#define NVIC_IP_PRI_20_WIDTH                     8
#define NVIC_IP_PRI_20(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_20_SHIFT))&NVIC_IP_PRI_20_MASK)
#define NVIC_IP_PRI_4_MASK                       0xFFu
#define NVIC_IP_PRI_4_SHIFT                      0
#define NVIC_IP_PRI_4_WIDTH                      8
#define NVIC_IP_PRI_4(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_4_SHIFT))&NVIC_IP_PRI_4_MASK)
#define NVIC_IP_PRI_16_MASK                      0xFFu
#define NVIC_IP_PRI_16_SHIFT                     0
#define NVIC_IP_PRI_16_WIDTH                     8
#define NVIC_IP_PRI_16(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_16_SHIFT))&NVIC_IP_PRI_16_MASK)
#define NVIC_IP_PRI_12_MASK                      0xFFu
#define NVIC_IP_PRI_12_SHIFT                     0
#define NVIC_IP_PRI_12_WIDTH                     8
#define NVIC_IP_PRI_12(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_12_SHIFT))&NVIC_IP_PRI_12_MASK)
#define NVIC_IP_PRI_8_MASK                       0xFFu
#define NVIC_IP_PRI_8_SHIFT                      0
#define NVIC_IP_PRI_8_WIDTH                      8
#define NVIC_IP_PRI_8(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_8_SHIFT))&NVIC_IP_PRI_8_MASK)
#define NVIC_IP_PRI_13_MASK                      0xFF00u
#define NVIC_IP_PRI_13_SHIFT                     8
#define NVIC_IP_PRI_13_WIDTH                     8
#define NVIC_IP_PRI_13(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_13_SHIFT))&NVIC_IP_PRI_13_MASK)
#define NVIC_IP_PRI_21_MASK                      0xFF00u
#define NVIC_IP_PRI_21_SHIFT                     8
#define NVIC_IP_PRI_21_WIDTH                     8
#define NVIC_IP_PRI_21(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_21_SHIFT))&NVIC_IP_PRI_21_MASK)
#define NVIC_IP_PRI_29_MASK                      0xFF00u
#define NVIC_IP_PRI_29_SHIFT                     8
#define NVIC_IP_PRI_29_WIDTH                     8
#define NVIC_IP_PRI_29(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_29_SHIFT))&NVIC_IP_PRI_29_MASK)
#define NVIC_IP_PRI_1_MASK                       0xFF00u
#define NVIC_IP_PRI_1_SHIFT                      8
#define NVIC_IP_PRI_1_WIDTH                      8
#define NVIC_IP_PRI_1(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_1_SHIFT))&NVIC_IP_PRI_1_MASK)
#define NVIC_IP_PRI_9_MASK                       0xFF00u
#define NVIC_IP_PRI_9_SHIFT                      8
#define NVIC_IP_PRI_9_WIDTH                      8
#define NVIC_IP_PRI_9(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_9_SHIFT))&NVIC_IP_PRI_9_MASK)
#define NVIC_IP_PRI_17_MASK                      0xFF00u
#define NVIC_IP_PRI_17_SHIFT                     8
#define NVIC_IP_PRI_17_WIDTH                     8
#define NVIC_IP_PRI_17(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_17_SHIFT))&NVIC_IP_PRI_17_MASK)
#define NVIC_IP_PRI_25_MASK                      0xFF00u
#define NVIC_IP_PRI_25_SHIFT                     8
#define NVIC_IP_PRI_25_WIDTH                     8
#define NVIC_IP_PRI_25(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_25_SHIFT))&NVIC_IP_PRI_25_MASK)
#define NVIC_IP_PRI_5_MASK                       0xFF00u
#define NVIC_IP_PRI_5_SHIFT                      8
#define NVIC_IP_PRI_5_WIDTH                      8
#define NVIC_IP_PRI_5(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_5_SHIFT))&NVIC_IP_PRI_5_MASK)
#define NVIC_IP_PRI_2_MASK                       0xFF0000u
#define NVIC_IP_PRI_2_SHIFT                      16
#define NVIC_IP_PRI_2_WIDTH                      8
#define NVIC_IP_PRI_2(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_2_SHIFT))&NVIC_IP_PRI_2_MASK)
#define NVIC_IP_PRI_26_MASK                      0xFF0000u
#define NVIC_IP_PRI_26_SHIFT                     16
#define NVIC_IP_PRI_26_WIDTH                     8
#define NVIC_IP_PRI_26(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_26_SHIFT))&NVIC_IP_PRI_26_MASK)
#define NVIC_IP_PRI_18_MASK                      0xFF0000u
#define NVIC_IP_PRI_18_SHIFT                     16
#define NVIC_IP_PRI_18_WIDTH                     8
#define NVIC_IP_PRI_18(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_18_SHIFT))&NVIC_IP_PRI_18_MASK)
#define NVIC_IP_PRI_14_MASK                      0xFF0000u
#define NVIC_IP_PRI_14_SHIFT                     16
#define NVIC_IP_PRI_14_WIDTH                     8
#define NVIC_IP_PRI_14(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_14_SHIFT))&NVIC_IP_PRI_14_MASK)
#define NVIC_IP_PRI_6_MASK                       0xFF0000u
#define NVIC_IP_PRI_6_SHIFT                      16
#define NVIC_IP_PRI_6_WIDTH                      8
#define NVIC_IP_PRI_6(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_6_SHIFT))&NVIC_IP_PRI_6_MASK)
#define NVIC_IP_PRI_30_MASK                      0xFF0000u
#define NVIC_IP_PRI_30_SHIFT                     16
#define NVIC_IP_PRI_30_WIDTH                     8
#define NVIC_IP_PRI_30(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_30_SHIFT))&NVIC_IP_PRI_30_MASK)
#define NVIC_IP_PRI_22_MASK                      0xFF0000u
#define NVIC_IP_PRI_22_SHIFT                     16
#define NVIC_IP_PRI_22_WIDTH                     8
#define NVIC_IP_PRI_22(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_22_SHIFT))&NVIC_IP_PRI_22_MASK)
#define NVIC_IP_PRI_10_MASK                      0xFF0000u
#define NVIC_IP_PRI_10_SHIFT                     16
#define NVIC_IP_PRI_10_WIDTH                     8
#define NVIC_IP_PRI_10(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_10_SHIFT))&NVIC_IP_PRI_10_MASK)
#define NVIC_IP_PRI_31_MASK                      0xFF000000u
#define NVIC_IP_PRI_31_SHIFT                     24
#define NVIC_IP_PRI_31_WIDTH                     8
#define NVIC_IP_PRI_31(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_31_SHIFT))&NVIC_IP_PRI_31_MASK)
#define NVIC_IP_PRI_27_MASK                      0xFF000000u
#define NVIC_IP_PRI_27_SHIFT                     24
#define NVIC_IP_PRI_27_WIDTH                     8
#define NVIC_IP_PRI_27(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_27_SHIFT))&NVIC_IP_PRI_27_MASK)
#define NVIC_IP_PRI_23_MASK                      0xFF000000u
#define NVIC_IP_PRI_23_SHIFT                     24
#define NVIC_IP_PRI_23_WIDTH                     8
#define NVIC_IP_PRI_23(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_23_SHIFT))&NVIC_IP_PRI_23_MASK)
#define NVIC_IP_PRI_3_MASK                       0xFF000000u
#define NVIC_IP_PRI_3_SHIFT                      24
#define NVIC_IP_PRI_3_WIDTH                      8
#define NVIC_IP_PRI_3(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_3_SHIFT))&NVIC_IP_PRI_3_MASK)
#define NVIC_IP_PRI_19_MASK                      0xFF000000u
#define NVIC_IP_PRI_19_SHIFT                     24
#define NVIC_IP_PRI_19_WIDTH                     8
#define NVIC_IP_PRI_19(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_19_SHIFT))&NVIC_IP_PRI_19_MASK)
#define NVIC_IP_PRI_15_MASK                      0xFF000000u
#define NVIC_IP_PRI_15_SHIFT                     24
#define NVIC_IP_PRI_15_WIDTH                     8
#define NVIC_IP_PRI_15(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_15_SHIFT))&NVIC_IP_PRI_15_MASK)
#define NVIC_IP_PRI_11_MASK                      0xFF000000u
#define NVIC_IP_PRI_11_SHIFT                     24
#define NVIC_IP_PRI_11_WIDTH                     8
#define NVIC_IP_PRI_11(x)                        (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_11_SHIFT))&NVIC_IP_PRI_11_MASK)
#define NVIC_IP_PRI_7_MASK                       0xFF000000u
#define NVIC_IP_PRI_7_SHIFT                      24
#define NVIC_IP_PRI_7_WIDTH                      8
#define NVIC_IP_PRI_7(x)                         (((uint32_t)(((uint32_t)(x))<<NVIC_IP_PRI_7_SHIFT))&NVIC_IP_PRI_7_MASK)

/*!
 * @}
 */ /* end of group NVIC_Register_Masks */


/* NVIC - Peripheral instance base addresses */
/** Peripheral NVIC base pointer */
#define NVIC_BASE_PTR                            ((NVIC_MemMapPtr)0xE000E100u)
/** Array initializer of NVIC peripheral base pointers */
#define NVIC_BASE_PTRS                           { NVIC_BASE_PTR }

/* ----------------------------------------------------------------------------
   -- NVIC - Register accessor macros
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup NVIC_Register_Accessor_Macros NVIC - Register accessor macros
 * @{
 */


/* NVIC - Register instance definitions */
/* NVIC */
#define NVIC_ISER                                NVIC_ISER_REG(NVIC_BASE_PTR)
#define NVIC_ICER                                NVIC_ICER_REG(NVIC_BASE_PTR)
#define NVIC_ISPR                                NVIC_ISPR_REG(NVIC_BASE_PTR)
#define NVIC_ICPR                                NVIC_ICPR_REG(NVIC_BASE_PTR)
#define NVIC_IPR0                                NVIC_IP_REG(NVIC_BASE_PTR,0)
#define NVIC_IPR1                                NVIC_IP_REG(NVIC_BASE_PTR,1)
#define NVIC_IPR2                                NVIC_IP_REG(NVIC_BASE_PTR,2)
#define NVIC_IPR3                                NVIC_IP_REG(NVIC_BASE_PTR,3)
#define NVIC_IPR4                                NVIC_IP_REG(NVIC_BASE_PTR,4)
#define NVIC_IPR5                                NVIC_IP_REG(NVIC_BASE_PTR,5)
#define NVIC_IPR6                                NVIC_IP_REG(NVIC_BASE_PTR,6)
#define NVIC_IPR7                                NVIC_IP_REG(NVIC_BASE_PTR,7)

/* NVIC - Register array accessors */
#define NVIC_IP(index)                           NVIC_IP_REG(NVIC_BASE_PTR,index)

/*!
 * @}
 */ /* end of group NVIC_Register_Accessor_Macros */


/*!
 * @}
 */ /* end of group NVIC_Peripheral */



/* ----------------------------------------------------------------------------
   -- SCB
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup SCB_Peripheral SCB
 * @{
 */

/** SCB - Peripheral register structure */
typedef struct SCB_MemMap {
  uint8_t RESERVED_0[8];
  uint32_t ACTLR;                                  /**< Auxiliary Control Register,, offset: 0x8 */
  uint8_t RESERVED_1[3316];
  uint32_t CPUID;                                  /**< CPUID Base Register, offset: 0xD00 */
  uint32_t ICSR;                                   /**< Interrupt Control and State Register, offset: 0xD04 */
  uint32_t VTOR;                                   /**< Vector Table Offset Register, offset: 0xD08 */
  uint32_t AIRCR;                                  /**< Application Interrupt and Reset Control Register, offset: 0xD0C */
  uint32_t SCR;                                    /**< System Control Register, offset: 0xD10 */
  uint32_t CCR;                                    /**< Configuration and Control Register, offset: 0xD14 */
  uint8_t RESERVED_2[4];
  uint32_t SHPR2;                                  /**< System Handler Priority Register 2, offset: 0xD1C */
  uint32_t SHPR3;                                  /**< System Handler Priority Register 3, offset: 0xD20 */
  uint32_t SHCSR;                                  /**< System Handler Control and State Register, offset: 0xD24 */
  uint8_t RESERVED_3[8];
  uint32_t DFSR;                                   /**< Debug Fault Status Register, offset: 0xD30 */
} volatile *SCB_MemMapPtr;

/* ----------------------------------------------------------------------------
   -- SCB - Register accessor macros
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup SCB_Register_Accessor_Macros SCB - Register accessor macros
 * @{
 */


/* SCB - Register accessors */
#define SCB_ACTLR_REG(base)                      ((base)->ACTLR)
#define SCB_CPUID_REG(base)                      ((base)->CPUID)
#define SCB_ICSR_REG(base)                       ((base)->ICSR)
#define SCB_VTOR_REG(base)                       ((base)->VTOR)
#define SCB_AIRCR_REG(base)                      ((base)->AIRCR)
#define SCB_SCR_REG(base)                        ((base)->SCR)
#define SCB_CCR_REG(base)                        ((base)->CCR)
#define SCB_SHPR2_REG(base)                      ((base)->SHPR2)
#define SCB_SHPR3_REG(base)                      ((base)->SHPR3)
#define SCB_SHCSR_REG(base)                      ((base)->SHCSR)
#define SCB_DFSR_REG(base)                       ((base)->DFSR)

/*!
 * @}
 */ /* end of group SCB_Register_Accessor_Macros */


/* ----------------------------------------------------------------------------
   -- SCB Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup SCB_Register_Masks SCB Register Masks
 * @{
 */

/* CPUID Bit Fields */
#define SCB_CPUID_REVISION_MASK                  0xFu
#define SCB_CPUID_REVISION_SHIFT                 0
#define SCB_CPUID_REVISION_WIDTH                 4
#define SCB_CPUID_REVISION(x)                    (((uint32_t)(((uint32_t)(x))<<SCB_CPUID_REVISION_SHIFT))&SCB_CPUID_REVISION_MASK)
#define SCB_CPUID_PARTNO_MASK                    0xFFF0u
#define SCB_CPUID_PARTNO_SHIFT                   4
#define SCB_CPUID_PARTNO_WIDTH                   12
#define SCB_CPUID_PARTNO(x)                      (((uint32_t)(((uint32_t)(x))<<SCB_CPUID_PARTNO_SHIFT))&SCB_CPUID_PARTNO_MASK)
#define SCB_CPUID_VARIANT_MASK                   0xF00000u
#define SCB_CPUID_VARIANT_SHIFT                  20
#define SCB_CPUID_VARIANT_WIDTH                  4
#define SCB_CPUID_VARIANT(x)                     (((uint32_t)(((uint32_t)(x))<<SCB_CPUID_VARIANT_SHIFT))&SCB_CPUID_VARIANT_MASK)
#define SCB_CPUID_IMPLEMENTER_MASK               0xFF000000u
#define SCB_CPUID_IMPLEMENTER_SHIFT              24
#define SCB_CPUID_IMPLEMENTER_WIDTH              8
#define SCB_CPUID_IMPLEMENTER(x)                 (((uint32_t)(((uint32_t)(x))<<SCB_CPUID_IMPLEMENTER_SHIFT))&SCB_CPUID_IMPLEMENTER_MASK)
/* ICSR Bit Fields */
#define SCB_ICSR_VECTPENDING_MASK                0x3F000u
#define SCB_ICSR_VECTPENDING_SHIFT               12
#define SCB_ICSR_VECTPENDING_WIDTH               6
#define SCB_ICSR_VECTPENDING(x)                  (((uint32_t)(((uint32_t)(x))<<SCB_ICSR_VECTPENDING_SHIFT))&SCB_ICSR_VECTPENDING_MASK)
#define SCB_ICSR_PENDSTCLR_MASK                  0x2000000u
#define SCB_ICSR_PENDSTCLR_SHIFT                 25
#define SCB_ICSR_PENDSTCLR_WIDTH                 1
#define SCB_ICSR_PENDSTCLR(x)                    (((uint32_t)(((uint32_t)(x))<<SCB_ICSR_PENDSTCLR_SHIFT))&SCB_ICSR_PENDSTCLR_MASK)
#define SCB_ICSR_PENDSTSET_MASK                  0x4000000u
#define SCB_ICSR_PENDSTSET_SHIFT                 26
#define SCB_ICSR_PENDSTSET_WIDTH                 1
#define SCB_ICSR_PENDSTSET(x)                    (((uint32_t)(((uint32_t)(x))<<SCB_ICSR_PENDSTSET_SHIFT))&SCB_ICSR_PENDSTSET_MASK)
#define SCB_ICSR_PENDSVCLR_MASK                  0x8000000u
#define SCB_ICSR_PENDSVCLR_SHIFT                 27
#define SCB_ICSR_PENDSVCLR_WIDTH                 1
#define SCB_ICSR_PENDSVCLR(x)                    (((uint32_t)(((uint32_t)(x))<<SCB_ICSR_PENDSVCLR_SHIFT))&SCB_ICSR_PENDSVCLR_MASK)
#define SCB_ICSR_PENDSVSET_MASK                  0x10000000u
#define SCB_ICSR_PENDSVSET_SHIFT                 28
#define SCB_ICSR_PENDSVSET_WIDTH                 1
#define SCB_ICSR_PENDSVSET(x)                    (((uint32_t)(((uint32_t)(x))<<SCB_ICSR_PENDSVSET_SHIFT))&SCB_ICSR_PENDSVSET_MASK)
#define SCB_ICSR_NMIPENDSET_MASK                 0x80000000u
#define SCB_ICSR_NMIPENDSET_SHIFT                31
#define SCB_ICSR_NMIPENDSET_WIDTH                1
#define SCB_ICSR_NMIPENDSET(x)                   (((uint32_t)(((uint32_t)(x))<<SCB_ICSR_NMIPENDSET_SHIFT))&SCB_ICSR_NMIPENDSET_MASK)
/* VTOR Bit Fields */
#define SCB_VTOR_TBLOFF_MASK                     0xFFFFFF80u
#define SCB_VTOR_TBLOFF_SHIFT                    7
#define SCB_VTOR_TBLOFF_WIDTH                    25
#define SCB_VTOR_TBLOFF(x)                       (((uint32_t)(((uint32_t)(x))<<SCB_VTOR_TBLOFF_SHIFT))&SCB_VTOR_TBLOFF_MASK)
/* AIRCR Bit Fields */
#define SCB_AIRCR_VECTCLRACTIVE_MASK             0x2u
#define SCB_AIRCR_VECTCLRACTIVE_SHIFT            1
#define SCB_AIRCR_VECTCLRACTIVE_WIDTH            1
#define SCB_AIRCR_VECTCLRACTIVE(x)               (((uint32_t)(((uint32_t)(x))<<SCB_AIRCR_VECTCLRACTIVE_SHIFT))&SCB_AIRCR_VECTCLRACTIVE_MASK)
#define SCB_AIRCR_SYSRESETREQ_MASK               0x4u
#define SCB_AIRCR_SYSRESETREQ_SHIFT              2
#define SCB_AIRCR_SYSRESETREQ_WIDTH              1
#define SCB_AIRCR_SYSRESETREQ(x)                 (((uint32_t)(((uint32_t)(x))<<SCB_AIRCR_SYSRESETREQ_SHIFT))&SCB_AIRCR_SYSRESETREQ_MASK)
#define SCB_AIRCR_ENDIANNESS_MASK                0x8000u
#define SCB_AIRCR_ENDIANNESS_SHIFT               15
#define SCB_AIRCR_ENDIANNESS_WIDTH               1
#define SCB_AIRCR_ENDIANNESS(x)                  (((uint32_t)(((uint32_t)(x))<<SCB_AIRCR_ENDIANNESS_SHIFT))&SCB_AIRCR_ENDIANNESS_MASK)
#define SCB_AIRCR_VECTKEY_MASK                   0xFFFF0000u
#define SCB_AIRCR_VECTKEY_SHIFT                  16
#define SCB_AIRCR_VECTKEY_WIDTH                  16
#define SCB_AIRCR_VECTKEY(x)                     (((uint32_t)(((uint32_t)(x))<<SCB_AIRCR_VECTKEY_SHIFT))&SCB_AIRCR_VECTKEY_MASK)
/* SCR Bit Fields */
#define SCB_SCR_SLEEPONEXIT_MASK                 0x2u
#define SCB_SCR_SLEEPONEXIT_SHIFT                1
#define SCB_SCR_SLEEPONEXIT_WIDTH                1
#define SCB_SCR_SLEEPONEXIT(x)                   (((uint32_t)(((uint32_t)(x))<<SCB_SCR_SLEEPONEXIT_SHIFT))&SCB_SCR_SLEEPONEXIT_MASK)
#define SCB_SCR_SLEEPDEEP_MASK                   0x4u
#define SCB_SCR_SLEEPDEEP_SHIFT                  2
#define SCB_SCR_SLEEPDEEP_WIDTH                  1
#define SCB_SCR_SLEEPDEEP(x)                     (((uint32_t)(((uint32_t)(x))<<SCB_SCR_SLEEPDEEP_SHIFT))&SCB_SCR_SLEEPDEEP_MASK)
#define SCB_SCR_SEVONPEND_MASK                   0x10u
#define SCB_SCR_SEVONPEND_SHIFT                  4
#define SCB_SCR_SEVONPEND_WIDTH                  1
#define SCB_SCR_SEVONPEND(x)                     (((uint32_t)(((uint32_t)(x))<<SCB_SCR_SEVONPEND_SHIFT))&SCB_SCR_SEVONPEND_MASK)
/* CCR Bit Fields */
#define SCB_CCR_UNALIGN_TRP_MASK                 0x8u
#define SCB_CCR_UNALIGN_TRP_SHIFT                3
#define SCB_CCR_UNALIGN_TRP_WIDTH                1
#define SCB_CCR_UNALIGN_TRP(x)                   (((uint32_t)(((uint32_t)(x))<<SCB_CCR_UNALIGN_TRP_SHIFT))&SCB_CCR_UNALIGN_TRP_MASK)
#define SCB_CCR_STKALIGN_MASK                    0x200u
#define SCB_CCR_STKALIGN_SHIFT                   9
#define SCB_CCR_STKALIGN_WIDTH                   1
#define SCB_CCR_STKALIGN(x)                      (((uint32_t)(((uint32_t)(x))<<SCB_CCR_STKALIGN_SHIFT))&SCB_CCR_STKALIGN_MASK)
/* SHPR2 Bit Fields */
#define SCB_SHPR2_PRI_11_MASK                    0xFF000000u
#define SCB_SHPR2_PRI_11_SHIFT                   24
#define SCB_SHPR2_PRI_11_WIDTH                   8
#define SCB_SHPR2_PRI_11(x)                      (((uint32_t)(((uint32_t)(x))<<SCB_SHPR2_PRI_11_SHIFT))&SCB_SHPR2_PRI_11_MASK)
/* SHPR3 Bit Fields */
#define SCB_SHPR3_PRI_14_MASK                    0xFF0000u
#define SCB_SHPR3_PRI_14_SHIFT                   16
#define SCB_SHPR3_PRI_14_WIDTH                   8
#define SCB_SHPR3_PRI_14(x)                      (((uint32_t)(((uint32_t)(x))<<SCB_SHPR3_PRI_14_SHIFT))&SCB_SHPR3_PRI_14_MASK)
#define SCB_SHPR3_PRI_15_MASK                    0xFF000000u
#define SCB_SHPR3_PRI_15_SHIFT                   24
#define SCB_SHPR3_PRI_15_WIDTH                   8
#define SCB_SHPR3_PRI_15(x)                      (((uint32_t)(((uint32_t)(x))<<SCB_SHPR3_PRI_15_SHIFT))&SCB_SHPR3_PRI_15_MASK)
/* SHCSR Bit Fields */
#define SCB_SHCSR_SVCALLPENDED_MASK              0x8000u
#define SCB_SHCSR_SVCALLPENDED_SHIFT             15
#define SCB_SHCSR_SVCALLPENDED_WIDTH             1
#define SCB_SHCSR_SVCALLPENDED(x)                (((uint32_t)(((uint32_t)(x))<<SCB_SHCSR_SVCALLPENDED_SHIFT))&SCB_SHCSR_SVCALLPENDED_MASK)
/* DFSR Bit Fields */
#define SCB_DFSR_HALTED_MASK                     0x1u
#define SCB_DFSR_HALTED_SHIFT                    0
#define SCB_DFSR_HALTED_WIDTH                    1
#define SCB_DFSR_HALTED(x)                       (((uint32_t)(((uint32_t)(x))<<SCB_DFSR_HALTED_SHIFT))&SCB_DFSR_HALTED_MASK)
#define SCB_DFSR_BKPT_MASK                       0x2u
#define SCB_DFSR_BKPT_SHIFT                      1
#define SCB_DFSR_BKPT_WIDTH                      1
#define SCB_DFSR_BKPT(x)                         (((uint32_t)(((uint32_t)(x))<<SCB_DFSR_BKPT_SHIFT))&SCB_DFSR_BKPT_MASK)
#define SCB_DFSR_DWTTRAP_MASK                    0x4u
#define SCB_DFSR_DWTTRAP_SHIFT                   2
#define SCB_DFSR_DWTTRAP_WIDTH                   1
#define SCB_DFSR_DWTTRAP(x)                      (((uint32_t)(((uint32_t)(x))<<SCB_DFSR_DWTTRAP_SHIFT))&SCB_DFSR_DWTTRAP_MASK)
#define SCB_DFSR_VCATCH_MASK                     0x8u
#define SCB_DFSR_VCATCH_SHIFT                    3
#define SCB_DFSR_VCATCH_WIDTH                    1
#define SCB_DFSR_VCATCH(x)                       (((uint32_t)(((uint32_t)(x))<<SCB_DFSR_VCATCH_SHIFT))&SCB_DFSR_VCATCH_MASK)
#define SCB_DFSR_EXTERNAL_MASK                   0x10u
#define SCB_DFSR_EXTERNAL_SHIFT                  4
#define SCB_DFSR_EXTERNAL_WIDTH                  1
#define SCB_DFSR_EXTERNAL(x)                     (((uint32_t)(((uint32_t)(x))<<SCB_DFSR_EXTERNAL_SHIFT))&SCB_DFSR_EXTERNAL_MASK)

/*!
 * @}
 */ /* end of group SCB_Register_Masks */


/* SCB - Peripheral instance base addresses */
/** Peripheral SystemControl base pointer */
#define SystemControl_BASE_PTR                   ((SCB_MemMapPtr)0xE000E000u)
/** Array initializer of SCB peripheral base pointers */
#define SCB_BASE_PTRS                            { SystemControl_BASE_PTR }

/* ----------------------------------------------------------------------------
   -- SCB - Register accessor macros
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup SCB_Register_Accessor_Macros SCB - Register accessor macros
 * @{
 */


/* SCB - Register instance definitions */
/* SystemControl */
#define SCB_ACTLR                                SCB_ACTLR_REG(SystemControl_BASE_PTR)
#define SCB_CPUID                                SCB_CPUID_REG(SystemControl_BASE_PTR)
#define SCB_ICSR                                 SCB_ICSR_REG(SystemControl_BASE_PTR)
#define SCB_VTOR                                 SCB_VTOR_REG(SystemControl_BASE_PTR)
#define SCB_AIRCR                                SCB_AIRCR_REG(SystemControl_BASE_PTR)
#define SCB_SCR                                  SCB_SCR_REG(SystemControl_BASE_PTR)
#define SCB_CCR                                  SCB_CCR_REG(SystemControl_BASE_PTR)
#define SCB_SHPR2                                SCB_SHPR2_REG(SystemControl_BASE_PTR)
#define SCB_SHPR3                                SCB_SHPR3_REG(SystemControl_BASE_PTR)
#define SCB_SHCSR                                SCB_SHCSR_REG(SystemControl_BASE_PTR)
#define SCB_DFSR                                 SCB_DFSR_REG(SystemControl_BASE_PTR)

/*!
 * @}
 */ /* end of group SCB_Register_Accessor_Macros */


/*!
 * @}
 */ /* end of group SCB_Peripheral */




#endif
/* __IO_Map_H */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
