/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Pins1.h
**     Project     : HeartBeat_PE
**     Processor   : SKEAZ64MLH4
**     Component   : PinSettings
**     Version     : Component 01.100, Driver 1.1, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-18, 14:28, # CodeGen: 10
**     Abstract    :
**
**     Settings    :
**          Component name                                 : Pins1
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : SKEAZ128LH4
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ACMP                       : 
**                Custom name                              : ACMP0
**                ACMP0: IN0 - Negative input 0            : <Automatic>
**                ACMP0: IN1 - Negative input 1            : <Automatic>
**                ACMP0: IN2 - Negative input 2            : <Automatic>
**                ACMP0: IN3 - Negative input 3            : DAC6b0_output
**                ACMP0: OUT - Output                      : <Automatic>
**                ACMP0: IN0 - Positive input 0            : <Automatic>
**                ACMP0: IN1 - Positive input 1            : <Automatic>
**                ACMP0: IN2 - Positive input 2            : <Automatic>
**                ACMP0: IN3 - Positive input 3            : DAC6b0_output
**                Custom name                              : ACMP1
**                ACMP1: IN0 - Negative input 0            : <Automatic>
**                ACMP1: IN1 - Negative input 1            : <Automatic>
**                ACMP1: IN2 - Negative input 2            : <Automatic>
**                ACMP1: IN3 - Negative input 3            : DAC6b1_output
**                ACMP1: OUT - Output                      : <Automatic>
**                ACMP1: IN0 - Positive input 0            : <Automatic>
**                ACMP1: IN1 - Positive input 1            : <Automatic>
**                ACMP1: IN2 - Positive input 2            : <Automatic>
**                ACMP1: IN3 - Positive input 3            : DAC6b1_output
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC
**                ADC: SE0 - Single-ended channel 0        : <Automatic>
**                ADC: SE1 - Single-ended channel 1        : <Automatic>
**                ADC: SE2 - Single-ended channel 2        : <Automatic>
**                ADC: SE3 - Single-ended channel 3        : <Automatic>
**                ADC: SE4 - Single-ended channel 4        : <Automatic>
**                ADC: SE5 - Single-ended channel 5        : <Automatic>
**                ADC: SE6 - Single-ended channel 6        : <Automatic>
**                ADC: SE7 - Single-ended channel 7        : <Automatic>
**                ADC: SE8 - Single-ended channel 8        : <Automatic>
**                ADC: SE9 - Single-ended channel 9        : <Automatic>
**                ADC: SE10 - Single-ended channel 10      : <Automatic>
**                ADC: SE11 - Single-ended channel 11      : <Automatic>
**                ADC: SE12 - Single-ended channel 12      : <Automatic>
**                ADC: SE13 - Single-ended channel 13      : <Automatic>
**                ADC: SE14 - Single-ended channel 14      : <Automatic>
**                ADC: SE15 - Single-ended channel 15      : <Automatic>
**                ADC: SE22 - Single-ended channel 22      : TempSensor
**                ADC: SE23 - Single-ended channel 23      : IntBandgap
**                ADC: SE29 - Single-ended channel 29      : VREFH/VDDA
**                ADC: ADC analog channel 30               : <Automatic>
**                ADC: Trigger input                       : <Automatic>
**                ADC: Voltage reference high              : VREFH/VDDA
**                ADC: Voltage reference low               : <Automatic>
**              Peripheral Type BP                         : 
**              Peripheral Type CRC                        : 
**                Custom name                              : CRC
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**                CoreDebug: CLK - Clock                   : <Automatic>
**                CoreDebug: DIO - Data input/output       : <Automatic>
**              Peripheral Type DWT                        : 
**              Peripheral Type FGPIO                      : 
**              Peripheral Type FTM                        : 
**                Custom name                              : FTM0
**                FTM0: CH0 - Channel 0                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM0: CH1 - Channel 1                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM0: TCLK - External clock input        : <Automatic>
**                Custom name                              : FTM1
**                FTM1: CH0 - Channel 0                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM1: CH1 - Channel 1                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM1: TCLK - External clock input        : <Automatic>
**                Custom name                              : FTM2
**                FTM2: CH0 - Channel 0                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM2: CH1 - Channel 1                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM2: CH2 - Channel 2                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM2: CH3 - Channel 3                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM2: CH4 - Channel 4                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM2: CH5 - Channel 5                    : <Automatic>
**                Direction                                : <Automatic>
**                FTM2: TCLK - External clock input        : <Automatic>
**                FTM2: FLT0 - Fault input 0               : <Automatic>
**                FTM2: FLT1 - Fault input 1               : <Automatic>
**                FTM2: FLT2 - Fault input 2               : <Automatic>
**                FTM2: FLT3 - Fault input 3               : <Automatic>
**                FTM2: Trigger input 0                    : <Automatic>
**                FTM2: Trigger input 1                    : FTM0_CH0_output
**                FTM2: Trigger input 2                    : FTM_sync
**              Peripheral Type FTMRE                      : 
**                Custom name                              : FTMRE
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA: Pin 0                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 1                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 2                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 3                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 4                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 5                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 6                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 7                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 8                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 9                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 10                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 11                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 12                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 13                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 14                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 15                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 16                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 17                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 18                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 19                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 20                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 21                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 22                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 23                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 24                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 25                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 26                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 27                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 28                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 29                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 30                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOA: Pin 31                            : <Automatic>
**                Direction                                : <Automatic>
**                Custom name                              : GPIOB
**                GPIOB: Pin 0                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 1                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 2                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 3                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 4                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 5                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 6                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 7                             : <Automatic>
**                Direction                                : Output
**                GPIOB: Pin 8                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 9                             : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 10                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 11                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 12                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 13                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 14                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 15                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 16                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 17                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 18                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 19                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 24                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 25                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 26                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 30                            : <Automatic>
**                Direction                                : <Automatic>
**                GPIOB: Pin 31                            : <Automatic>
**                Direction                                : <Automatic>
**                Custom name                              : GPIOC
**                GPIOC: Pin 4                             : <Automatic>
**                Direction                                : <Automatic>
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0: SCL - Serial clock                 : <Automatic>
**                I2C0: 4WSCLOUT - 4 wire serial clock     : <Automatic>
**                I2C0: SDA - Serial data                  : <Automatic>
**                I2C0: 4WSDAOUT - 4 wire serial data      : <Automatic>
**                Custom name                              : I2C1
**                I2C1: SCL - Serial clock                 : <Automatic>
**                I2C1: SDA - Serial data                  : <Automatic>
**              Peripheral Type ICS                        : 
**                Custom name                              : ICS
**              Peripheral Type IRQ                        : 
**                Custom name                              : IRQ
**                IRQ: Interrupt request                   : <Automatic>
**              Peripheral Type KBI                        : 
**                Custom name                              : KBI0
**                KBI0: P0 - Keyboard interrupt 0          : <Automatic>
**                KBI0: P1 - Keyboard interrupt 1          : <Automatic>
**                KBI0: P2 - Keyboard interrupt 2          : <Automatic>
**                KBI0: P3 - Keyboard interrupt 3          : <Automatic>
**                KBI0: P4 - Keyboard interrupt 4          : <Automatic>
**                KBI0: P5 - Keyboard interrupt 5          : <Automatic>
**                KBI0: P6 - Keyboard interrupt 6          : <Automatic>
**                KBI0: P7 - Keyboard interrupt 7          : <Automatic>
**                KBI0: P8 - Keyboard interrupt 8          : <Automatic>
**                KBI0: P9 - Keyboard interrupt 9          : <Automatic>
**                KBI0: P10 - Keyboard interrupt 10        : <Automatic>
**                KBI0: P11 - Keyboard interrupt 11        : <Automatic>
**                KBI0: P12 - Keyboard interrupt 12        : <Automatic>
**                KBI0: P13 - Keyboard interrupt 13        : <Automatic>
**                KBI0: P14 - Keyboard interrupt 14        : <Automatic>
**                KBI0: P15 - Keyboard interrupt 15        : <Automatic>
**                KBI0: P16 - Keyboard interrupt 16        : <Automatic>
**                KBI0: P17 - Keyboard interrupt 17        : <Automatic>
**                KBI0: P18 - Keyboard interrupt 18        : <Automatic>
**                KBI0: P19 - Keyboard interrupt 19        : <Automatic>
**                KBI0: P20 - Keyboard interrupt 20        : <Automatic>
**                KBI0: P21 - Keyboard interrupt 21        : <Automatic>
**                KBI0: P22 - Keyboard interrupt 22        : <Automatic>
**                KBI0: P23 - Keyboard interrupt 23        : <Automatic>
**                KBI0: P24 - Keyboard interrupt 24        : <Automatic>
**                KBI0: P25 - Keyboard interrupt 25        : <Automatic>
**                KBI0: P26 - Keyboard interrupt 26        : <Automatic>
**                KBI0: P27 - Keyboard interrupt 27        : <Automatic>
**                KBI0: P28 - Keyboard interrupt 28        : <Automatic>
**                KBI0: P29 - Keyboard interrupt 29        : <Automatic>
**                KBI0: P30 - Keyboard interrupt 30        : <Automatic>
**                KBI0: P31 - Keyboard interrupt 31        : <Automatic>
**                Custom name                              : KBI1
**                KBI1: P0 - Keyboard interrupt 0          : <Automatic>
**                KBI1: P1 - Keyboard interrupt 1          : <Automatic>
**                KBI1: P2 - Keyboard interrupt 2          : <Automatic>
**                KBI1: P3 - Keyboard interrupt 3          : <Automatic>
**                KBI1: P4 - Keyboard interrupt 4          : <Automatic>
**                KBI1: P5 - Keyboard interrupt 5          : <Automatic>
**                KBI1: P6 - Keyboard interrupt 6          : <Automatic>
**                KBI1: P7 - Keyboard interrupt 7          : <Automatic>
**                KBI1: P8 - Keyboard interrupt 8          : <Automatic>
**                KBI1: P9 - Keyboard interrupt 9          : <Automatic>
**                KBI1: P10 - Keyboard interrupt 10        : <Automatic>
**                KBI1: P11 - Keyboard interrupt 11        : <Automatic>
**                KBI1: P12 - Keyboard interrupt 12        : <Automatic>
**                KBI1: P13 - Keyboard interrupt 13        : <Automatic>
**                KBI1: P14 - Keyboard interrupt 14        : <Automatic>
**                KBI1: P15 - Keyboard interrupt 15        : <Automatic>
**                KBI1: P16 - Keyboard interrupt 16        : <Automatic>
**                KBI1: P17 - Keyboard interrupt 17        : <Automatic>
**                KBI1: P18 - Keyboard interrupt 18        : <Automatic>
**                KBI1: P19 - Keyboard interrupt 19        : <Automatic>
**                KBI1: P24 - Keyboard interrupt 24        : <Automatic>
**                KBI1: P25 - Keyboard interrupt 25        : <Automatic>
**                KBI1: P26 - Keyboard interrupt 26        : <Automatic>
**                KBI1: P30 - Keyboard interrupt 30        : <Automatic>
**                KBI1: P31 - Keyboard interrupt 31        : <Automatic>
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MSCAN                      : 
**                Custom name                              : MSCAN
**                MSCAN: RX - Receiver input               : <Automatic>
**                MSCAN: TX - Transmitter output           : <Automatic>
**              Peripheral Type NV                         : 
**                Custom name                              : FTMRE_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC
**                OSC: External clock/oscillator input     : <Automatic>
**                OSC: Oscillator output                   : <Automatic>
**              Peripheral Type PIT                        : 
**                Custom name                              : PIT
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORT
**              Peripheral Type PWT                        : 
**                Custom name                              : PWT
**                PWT: IN0 - Input 0                       : <Automatic>
**                PWT: IN1 - Input 1                       : <Automatic>
**                PWT: IN2 - Input 2                       : <Automatic>
**                PWT: IN2 - Input 3                       : <Automatic>
**                PWT: TCLK - External clock input         : <Automatic>
**              Peripheral Type ROM                        : 
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC: Clock output                        : <Automatic>
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM: Bus clok output                     : <Automatic>
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0: MISO - Master data in, slave data out: <Automatic>
**                Direction                                : <Automatic>
**                SPI0: MOSI - Master data out, slave data in: <Automatic>
**                Direction                                : <Automatic>
**                SPI0: SCK - Serial clock                 : <Automatic>
**                Direction                                : <Automatic>
**                SPI0: PCS - Peripheral chip select       : <Automatic>
**                Direction                                : <Automatic>
**                Custom name                              : SPI1
**                SPI1: MISO - Master data in, slave data out: <Automatic>
**                Direction                                : <Automatic>
**                SPI1: MOSI - Master data out, slave data in: <Automatic>
**                Direction                                : <Automatic>
**                SPI1: SCK - Serial clock                 : <Automatic>
**                Direction                                : <Automatic>
**                SPI1: PCS - Peripheral chip select       : <Automatic>
**                Direction                                : <Automatic>
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type UART                       : 
**                Custom name                              : UART0
**                UART0: RX - Receive data                 : <Automatic>
**                UART0: TX - Transmit data                : <Automatic>
**                UART0: TX modulator input                : FTM0_CH0_output
**                Custom name                              : UART1
**                UART1: RX - Receive data                 : <Automatic>
**                UART1: TX - Transmit data                : <Automatic>
**                Custom name                              : UART2
**                UART2: RX - Receive data                 : <Automatic>
**                UART2: TX - Transmit data                : <Automatic>
**              Peripheral Type WDOG                       : 
**                Custom name                              : WDOG
**              Non-peripheral pins                        : 
**                NMI                                      : <Automatic>
**                RESET                                    : <Automatic>
**            Electrical properties                        : 
**              Pin 1: PTD1/KBI0_P25/FTM2_CH3/SPI1_MOSI    : 
**                Custom name, Signal name                 : PTD1/KBI0_P25/FTM2_CH3/SPI1_MOSI
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 2: PTD0/KBI0_P24/FTM2_CH2/SPI1_SCK     : 
**                Custom name, Signal name                 : PTD0/KBI0_P24/FTM2_CH2/SPI1_SCK
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 3: PTH7/KBI1_P31/PWT_IN1               : 
**                Custom name, Signal name                 : PTH7/KBI1_P31/PWT_IN1
**                Pull enable                              : <Automatic>
**              Pin 4: PTH6/KBI1_P30                       : 
**                Custom name, Signal name                 : PTH6/KBI1_P30
**                Pull enable                              : <Automatic>
**              Pin 5: PTE7/KBI1_P7/TCLK2/FTM1_CH1/CAN0_TX : 
**                Custom name, Signal name                 : PTE7/KBI1_P7/TCLK2/FTM1_CH1/CAN0_TX
**                Pull enable                              : <Automatic>
**              Pin 6: PTH2/KBI1_P26/BUSOUT/FTM1_CH0/CAN0_RX: 
**                Custom name, Signal name                 : PTH2/KBI1_P26/BUSOUT/FTM1_CH0/CAN0_RX
**                Pull enable                              : <Automatic>
**              Pin 7: VDD8                                : 
**                Custom name, Signal name                 : VDD8
**              Pin 8: VREFH/VDDA                          : 
**                Custom name, Signal name                 : VREFH/VDDA
**              Pin 9: VREFL                               : 
**                Custom name, Signal name                 : VREFL
**              Pin 10: VSSA/VSS                           : 
**                Custom name, Signal name                 : VSSA/VSS
**              Pin 11: PTB7/KBI0_P15/I2C0_SCL/EXTAL       : 
**                Custom name, Signal name                 : PTB7/KBI0_P15/I2C0_SCL/EXTAL
**                Pull enable                              : <Automatic>
**              Pin 12: PTB6/KBI0_P14/I2C0_SDA/XTAL        : 
**                Custom name, Signal name                 : PTB6/KBI0_P14/I2C0_SDA/XTAL
**                Pull enable                              : <Automatic>
**              Pin 13: PTI4/IRQ                           : 
**                Custom name, Signal name                 : PTI4/IRQ
**                Pull enable                              : <Automatic>
**              Pin 14: PTH1/KBI1_P25/FTM2_CH1             : 
**                Custom name, Signal name                 : PTH1/KBI1_P25/FTM2_CH1
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 15: PTH0/KBI1_P24/FTM2_CH0             : 
**                Custom name, Signal name                 : PTH0/KBI1_P24/FTM2_CH0
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 16: PTE6/KBI1_P6                       : 
**                Custom name, Signal name                 : PTE6/KBI1_P6
**                Pull enable                              : <Automatic>
**              Pin 17: PTE5/KBI1_P5                       : 
**                Custom name, Signal name                 : PTE5/KBI1_P5
**                Pull enable                              : <Automatic>
**              Pin 18: PTB5/KBI0_P13/FTM2_CH5/SPI0_PCS/ACMP1_OUT: 
**                Custom name, Signal name                 : PTB5/KBI0_P13/FTM2_CH5/SPI0_PCS/ACMP1_OUT
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 19: PTB4/KBI0_P12/FTM2_CH4/SPI0_MISO/ACMP1_IN2/NMI_b: 
**                Custom name, Signal name                 : PTB4/KBI0_P12/FTM2_CH4/SPI0_MISO/ACMP1_IN2/NMI_b
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 20: PTC3/KBI0_P19/FTM2_CH3/ADC0_SE11   : 
**                Custom name, Signal name                 : PTC3/KBI0_P19/FTM2_CH3/ADC0_SE11
**                Pull enable                              : <Automatic>
**              Pin 21: PTC2/KBI0_P18/FTM2_CH2/ADC0_SE10   : 
**                Custom name, Signal name                 : PTC2/KBI0_P18/FTM2_CH2/ADC0_SE10
**                Pull enable                              : <Automatic>
**              Pin 22: PTD7/KBI0_P31/UART2_TX             : 
**                Custom name, Signal name                 : PTD7/KBI0_P31/UART2_TX
**                Pull enable                              : <Automatic>
**              Pin 23: PTD6/KBI0_P30/UART2_RX             : 
**                Custom name, Signal name                 : PTD6/KBI0_P30/UART2_RX
**                Pull enable                              : <Automatic>
**              Pin 24: PTD5/KBI0_P29/PWT_IN0              : 
**                Custom name, Signal name                 : PTD5/KBI0_P29/PWT_IN0
**                Pull enable                              : <Automatic>
**              Pin 25: PTC1/KBI0_P17/FTM2_CH1/ADC0_SE9    : 
**                Custom name, Signal name                 : PTC1/KBI0_P17/FTM2_CH1/ADC0_SE9
**                Pull enable                              : <Automatic>
**              Pin 26: PTC0/KBI0_P16/FTM2_CH0/ADC0_SE8    : 
**                Custom name, Signal name                 : PTC0/KBI0_P16/FTM2_CH0/ADC0_SE8
**                Pull enable                              : <Automatic>
**              Pin 27: PTF7/KBI1_P15/ADC0_SE15            : 
**                Custom name, Signal name                 : PTF7/KBI1_P15/ADC0_SE15
**                Pull enable                              : <Automatic>
**              Pin 28: PTF6/KBI1_P14/ADC0_SE14            : 
**                Custom name, Signal name                 : PTF6/KBI1_P14/ADC0_SE14
**                Pull enable                              : <Automatic>
**              Pin 29: PTF5/KBI1_P13/ADC0_SE13            : 
**                Custom name, Signal name                 : PTF5/KBI1_P13/ADC0_SE13
**                Pull enable                              : <Automatic>
**              Pin 30: PTF4/KBI1_P12/ADC0_SE12            : 
**                Custom name, Signal name                 : PTF4/KBI1_P12/ADC0_SE12
**                Pull enable                              : <Automatic>
**              Pin 31: PTB3/KBI0_P11/SPI0_MOSI/FTM0_CH1/ADC0_SE7: 
**                Custom name, Signal name                 : PTB3/KBI0_P11/SPI0_MOSI/FTM0_CH1/ADC0_SE7
**                Pull enable                              : <Automatic>
**              Pin 32: PTB2/KBI0_P10/SPI0_SCK/FTM0_CH0/ADC0_SE6: 
**                Custom name, Signal name                 : PTB2/KBI0_P10/SPI0_SCK/FTM0_CH0/ADC0_SE6
**                Pull enable                              : <Automatic>
**              Pin 33: PTB1/KBI0_P9/UART0_TX/ADC0_SE5     : 
**                Custom name, Signal name                 : PTB1/KBI0_P9/UART0_TX/ADC0_SE5
**                Pull enable                              : <Automatic>
**              Pin 34: PTB0/KBI0_P8/UART0_RX/PWT_IN1/ADC0_SE4: 
**                Custom name, Signal name                 : PTB0/KBI0_P8/UART0_RX/PWT_IN1/ADC0_SE4
**                Pull enable                              : <Automatic>
**              Pin 35: PTF3/KBI1_P11/UART1_TX             : 
**                Custom name, Signal name                 : PTF3/KBI1_P11/UART1_TX
**                Pull enable                              : <Automatic>
**              Pin 36: PTF2/KBI1_P10/UART1_RX             : 
**                Custom name, Signal name                 : PTF2/KBI1_P10/UART1_RX
**                Pull enable                              : <Automatic>
**              Pin 37: PTA7/KBI0_P7/FTM2_FLT2/ACMP1_IN1/ADC0_SE3: 
**                Custom name, Signal name                 : PTA7/KBI0_P7/FTM2_FLT2/ACMP1_IN1/ADC0_SE3
**                Pull enable                              : <Automatic>
**              Pin 38: PTA6/KBI0_P6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2: 
**                Custom name, Signal name                 : PTA6/KBI0_P6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2
**                Pull enable                              : <Automatic>
**              Pin 39: PTE4/KBI1_P4                       : 
**                Custom name, Signal name                 : PTE4/KBI1_P4
**                Pull enable                              : <Automatic>
**              Pin 40: VSS48                              : 
**                Custom name, Signal name                 : VSS48
**              Pin 41: VDD49                              : 
**                Custom name, Signal name                 : VDD49
**              Pin 42: PTF1/KBI1_P9/FTM2_CH1              : 
**                Custom name, Signal name                 : PTF1/KBI1_P9/FTM2_CH1
**                Pull enable                              : <Automatic>
**              Pin 43: PTF0/KBI1_P8/FTM2_CH0              : 
**                Custom name, Signal name                 : PTF0/KBI1_P8/FTM2_CH0
**                Pull enable                              : <Automatic>
**              Pin 44: PTD4/KBI0_P28                      : 
**                Custom name, Signal name                 : PTD4/KBI0_P28
**                Pull enable                              : <Automatic>
**              Pin 45: PTD3/KBI0_P27/SPI1_PCS             : 
**                Custom name, Signal name                 : PTD3/KBI0_P27/SPI1_PCS
**                Pull enable                              : <Automatic>
**              Pin 46: PTD2/KBI0_P26/SPI1_MISO            : 
**                Custom name, Signal name                 : PTD2/KBI0_P26/SPI1_MISO
**                Pull enable                              : <Automatic>
**              Pin 47: PTA3/KBI0_P3/UART0_TX/I2C0_SCL     : 
**                Custom name, Signal name                 : PTA3/KBI0_P3/UART0_TX/I2C0_SCL
**                Pull enable                              : <Automatic>
**              Pin 48: PTA2/KBI0_P2/UART0_RX/I2C0_SDA     : 
**                Custom name, Signal name                 : PTA2/KBI0_P2/UART0_RX/I2C0_SDA
**                Pull enable                              : <Automatic>
**              Pin 49: PTA1/KBI0_P1/FTM0_CH1/I2C0_4WSDAOUT/ACMP0_IN1/ADC0_SE1: 
**                Custom name, Signal name                 : PTA1/KBI0_P1/FTM0_CH1/I2C0_4WSDAOUT/ACMP0_IN1/ADC0_SE1
**                Pull enable                              : <Automatic>
**              Pin 50: PTA0/KBI0_P0/FTM0_CH0/I2C0_4WSCLOUT/ACMP0_IN0/ADC0_SE0: 
**                Custom name, Signal name                 : PTA0/KBI0_P0/FTM0_CH0/I2C0_4WSCLOUT/ACMP0_IN0/ADC0_SE0
**                Pull enable                              : <Automatic>
**              Pin 51: PTC7/KBI0_P23/UART1_TX/CAN0_TX     : 
**                Custom name, Signal name                 : PTC7/KBI0_P23/UART1_TX/CAN0_TX
**                Pull enable                              : <Automatic>
**              Pin 52: PTC6/KBI0_P22/UART1_RX/CAN0_RX     : 
**                Custom name, Signal name                 : PTC6/KBI0_P22/UART1_RX/CAN0_RX
**                Pull enable                              : <Automatic>
**              Pin 53: PTE3/KBI1_P3/SPI0_PCS              : 
**                Custom name, Signal name                 : PTE3/KBI1_P3/SPI0_PCS
**                Pull enable                              : <Automatic>
**              Pin 54: PTE2/KBI1_P2/SPI0_MISO/PWT_IN0     : 
**                Custom name, Signal name                 : PTE2/KBI1_P2/SPI0_MISO/PWT_IN0
**                Pull enable                              : <Automatic>
**              Pin 55: PTG3/KBI1_P19                      : 
**                Custom name, Signal name                 : PTG3/KBI1_P19
**                Pull enable                              : <Automatic>
**              Pin 56: PTG2/KBI1_P18                      : 
**                Custom name, Signal name                 : PTG2/KBI1_P18
**                Pull enable                              : <Automatic>
**              Pin 57: PTG1/KBI1_P17                      : 
**                Custom name, Signal name                 : PTG1/KBI1_P17
**                Pull enable                              : <Automatic>
**              Pin 58: PTG0/KBI1_P16                      : 
**                Custom name, Signal name                 : PTG0/KBI1_P16
**                Pull enable                              : <Automatic>
**              Pin 59: PTE1/KBI1_P1/SPI0_MOSI/I2C1_SCL    : 
**                Custom name, Signal name                 : PTE1/KBI1_P1/SPI0_MOSI/I2C1_SCL
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 60: PTE0/KBI1_P0/SPI0_SCK/TCLK1/I2C1_SDA: 
**                Custom name, Signal name                 : PTE0/KBI1_P0/SPI0_SCK/TCLK1/I2C1_SDA
**                Pull enable                              : <Automatic>
**                High drive enable                        : <Automatic>
**              Pin 61: PTC5/KBI0_P21/FTM1_CH1/RTCO        : 
**                Custom name, Signal name                 : PTC5/KBI0_P21/FTM1_CH1/RTCO
**                Pull enable                              : <Automatic>
**              Pin 62: PTC4/KBI0_P20/RTCO/FTM1_CH0/ACMP0_IN2/SWD_CLK: 
**                Custom name, Signal name                 : PTC4/KBI0_P20/RTCO/FTM1_CH0/ACMP0_IN2/SWD_CLK
**                Pull enable                              : <Automatic>
**              Pin 63: PTA5/KBI0_P5/IRQ/TCLK0/RESET_b     : 
**                Custom name, Signal name                 : PTA5/KBI0_P5/IRQ/TCLK0/RESET_b
**                Pull enable                              : <Automatic>
**              Pin 64: PTA4/KBI0_P4/ACMP0_OUT/SWD_DIO     : 
**                Custom name, Signal name                 : PTA4/KBI0_P4/ACMP0_OUT/SWD_DIO
**                Pull enable                              : <Automatic>
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Pins1.h
** @version 1.1
** @brief
**
*/         
/*!
**  @addtogroup Pins1_module Pins1 module documentation
**  @{
*/         

#ifndef Pins1_H_
#define Pins1_H_

/* MODULE Pins1. */

/* Including shared modules, which are used in the whole project */
#include "Init_Config.h"




/* END Pins1. */
#endif /* #ifndef __Pins1_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
